package com.jencao.mywork.ui.theme

import androidx.compose.ui.graphics.Color

// 浅色主题配色（沉静的青绿 productivity 风格，背景偏中性灰以便新拟物阴影可读）
val LightPrimary = Color(0xFF3F8E7D)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBFE9DD)
val LightOnPrimaryContainer = Color(0xFF002019)
val LightSecondary = Color(0xFF5C7A86)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD5E7EC)
val LightOnSecondaryContainer = Color(0xFF0C1F25)
val LightTertiary = Color(0xFFB5794E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFAD9C2)
val LightOnTertiaryContainer = Color(0xFF321202)
val LightBackground = Color(0xFFE9EDEC)
val LightOnBackground = Color(0xFF1A1F1D)
val LightSurface = Color(0xFFE9EDEC)
val LightOnSurface = Color(0xFF1A1F1D)
val LightSurfaceVariant = Color(0xFFD7DEDC)
val LightOnSurfaceVariant = Color(0xFF3F4845)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightOutline = Color(0xFF6F7976)

// 深色主题配色
val DarkPrimary = Color(0xFF7FCBB9)
val DarkOnPrimary = Color(0xFF00382C)
val DarkPrimaryContainer = Color(0xFF00503C)
val DarkOnPrimaryContainer = Color(0xFFA7F4D4)
val DarkSecondary = Color(0xFFB9D3D9)
val DarkOnSecondary = Color(0xFF1C3338)
val DarkSecondaryContainer = Color(0xFF33484F)
val DarkOnSecondaryContainer = Color(0xFFD5E7EC)
val DarkTertiary = Color(0xFFE0B68F)
val DarkOnTertiary = Color(0xFF4A2809)
val DarkTertiaryContainer = Color(0xFF643B1C)
val DarkOnTertiaryContainer = Color(0xFFFAD9C2)
val DarkBackground = Color(0xFF1A1E1D)
val DarkOnBackground = Color(0xFFE1E3E0)
val DarkSurface = Color(0xFF1A1E1D)
val DarkOnSurface = Color(0xFFE1E3E0)
val DarkSurfaceVariant = Color(0xFF3F4845)
val DarkOnSurfaceVariant = Color(0xFFBFC9C5)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkOutline = Color(0xFF89938F)
