package com.jencao.mywork.ui.theme

import androidx.compose.ui.graphics.Color

// 浅色主题配色（沉静的青绿 productivity 风格）
val LightPrimary = Color(0xFF2E7D62)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB8F0D8)
val LightOnPrimaryContainer = Color(0xFF002114)
val LightSecondary = Color(0xFF4F8071)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD1E8E0)
val LightOnSecondaryContainer = Color(0xFF08201B)
val LightTertiary = Color(0xFF4D6075)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD3E4F8)
val LightOnTertiaryContainer = Color(0xFF081D2F)
val LightBackground = Color(0xFFFCFDF9)
val LightOnBackground = Color(0xFF191C1A)
val LightSurface = Color(0xFFFCFDF9)
val LightOnSurface = Color(0xFF191C1A)
val LightSurfaceVariant = Color(0xFFDCE5DF)
val LightOnSurfaceVariant = Color(0xFF404944)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightOutline = Color(0xFF707971)

// 深色主题配色
val DarkPrimary = Color(0xFF87D9B4)
val DarkOnPrimary = Color(0xFF00382A)
val DarkPrimaryContainer = Color(0xFF00503C)
val DarkOnPrimaryContainer = Color(0xFFA7F4D4)
val DarkSecondary = Color(0xFFB5CCC2)
val DarkOnSecondary = Color(0xFF1C352D)
val DarkSecondaryContainer = Color(0xFF33655A)
val DarkOnSecondaryContainer = Color(0xFFD1E8E0)
val DarkTertiary = Color(0xFFB5C9E0)
val DarkOnTertiary = Color(0xFF203448)
val DarkTertiaryContainer = Color(0xFF36495C)
val DarkOnTertiaryContainer = Color(0xFFD3E4F8)
val DarkBackground = Color(0xFF191C1A)
val DarkOnBackground = Color(0xFFE1E3DE)
val DarkSurface = Color(0xFF191C1A)
val DarkOnSurface = Color(0xFFE1E3DE)
val DarkSurfaceVariant = Color(0xFF404944)
val DarkOnSurfaceVariant = Color(0xFFC0C9C3)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkOutline = Color(0xFF8A938B)
